# Generated by Django 6.0.7 on 2026-07-30 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Child', 'Child'), ('Elderly', 'Elderly'), ('Adult', 'Adult'), ('Disabled', 'Disabled')], default='Adult', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_seen_location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('Searching', 'Searching'), ('Found', 'Found'), ('Closed', 'Closed')], default='Searching', max_length=20)),
                ('contact_mobile', models.CharField(blank=True, max_length=15)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_person_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
