# Generated by Django 6.0.7 on 2026-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_reports/'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
