# Generated by Django 6.0.7 on 2026-07-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LostFoundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported Lost"),
                            ("FOUND", "Found in Storage"),
                            ("CLAIM_PENDING", "Claim Pending Verification"),
                            ("RETURNED", "Returned to Owner"),
                        ],
                        default="REPORTED",
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(max_length=20)),
                (
                    "qr_claim_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
