# Generated by Django 6.0.7 on 2026-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
