# Generated by Django 6.0.7 on 2026-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_lostfounditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_found/'),
        ),
    ]
