# Generated by Django 6.0.7 on 2026-07-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PilgrimageMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("marathi_name", models.CharField(max_length=200)),
                ("significance", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("day_number", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Saint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("marathi_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("era", models.CharField(max_length=100)),
                ("biography", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Abhang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("marathi_title", models.CharField(max_length=200)),
                ("lyrics", models.TextField()),
                ("translation", models.TextField(blank=True, null=True)),
                ("audio_url", models.URLField(blank=True, null=True)),
                (
                    "saint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abhangs",
                        to="heritage.saint",
                    ),
                ),
            ],
        ),
    ]
