# Generated by Django 6.0.7 on 2026-08-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abhang',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AddField(
            model_name='abhang',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='abhang',
            name='category',
            field=models.CharField(choices=[('Abhang', 'Abhang (अभंग)'), ('Haripath', 'Haripath (हरिपाठ)'), ('Pasaydan', 'Pasaydan (पसायदान)'), ('Bhajan', 'Bhajan (भजन)'), ('Kirtan', 'Kirtan (कीर्तन)'), ('Information', 'Information Guide (माहिती)')], default='Abhang', max_length=50),
        ),
        migrations.AddField(
            model_name='abhang',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='abhang',
            name='duration',
            field=models.CharField(blank=True, default='03:30', max_length=50),
        ),
        migrations.AddField(
            model_name='abhang',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='abhang',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='abhang',
            name='lyrics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='abhang',
            name='saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abhangs', to='heritage.saint'),
        ),
        migrations.AlterField(
            model_name='saint',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='saint',
            name='era',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='saint',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
