# Generated by Django 6.0.7 on 2026-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0003_livelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
