# Generated by Django 6.0.7 on 2026-08-04 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Water', 'Water Point / Tanker'), ('Medical', 'Medical Camp / First Aid'), ('Food', 'Food / Annadhana Stall'), ('Toilets', 'Public Toilet / Sanitation'), ('Shelter', 'Shelter / Rest Camp'), ('Police', 'Police Checkpoint / Security'), ('Help Desk', 'Help Desk / Information'), ('Parking', 'Vehicle Parking Area'), ('Other', 'Other Service')], default='Water', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Available', 'Available'), ('Busy', 'Busy'), ('Closed', 'Closed')], default='Active', max_length=50)),
                ('capacity_info', models.CharField(blank=True, default='', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
